---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  client_rb:
    environment: _default
  attributes:
    platformstack:
      cloudbackup:
        enabled: false
      cloud_monitoring:
        enabled: false
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: centos-6.5
    run_list:
    - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[phpstack::application_php]
      - recipe[phpstack::mysql_master]
    attributes:
      mysql:
        server_root_password: "randompass"
        server_repl_password: "randompass"
        server_debian_password: "randompass"
      mysql-multi:
        slaves: [] 

  - name: mysql-master
    run_list:
      - recipe[phpstack::mysql_master]
    attributes:
      mysql:
        server_root_password: "randompass"
        server_repl_password: "randompass"
        server_debian_password: "randompass"
      holland:
        password: "randompass"

  - name: mysql-slave
    run_list:
      - recipe[phpstack::mysql_slave]
    attributes:
      mysql:
        server_root_password: "randompass"
        server_repl_password: "randompass"
        server_debian_password: "randompass"
      holland:
        password: "randompass"

  - name: application_php
    run_list:
      - recipe[phpstack::application_php]
      - recipe[phpstack::mysql_base]
    attributes:
      mysql:
        server_root_password: "randompass"
        server_repl_password: "randompass"
        server_debian_password: "randompass"

  - name: mongodb
    run_list:
      - recipe[phpstack::mongodb_standalone]

  - name: varnish
    run_list:
      - recipe[phpstack::varnish]

  - name: memcached
    run_list:
      - recipe[phpstack::memcache]
