---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  attributes:
    phpstack:
      demo:
        enabled: true
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true
    mysql:
      server_root_password: "randompass"
      server_repl_password: "randompass"
      server_debian_password: "randompass"
    holland:
      password: "randompass"

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: centos-6.5
    run_list:
    - recipe[yum]

suites:
  - name: aio-apache
    run_list:
      - recipe[phpstack::mysql_base]
      - recipe[phpstack::postgresql_base]
      - recipe[phpstack::mongodb_standalone]
      - recipe[phpstack::memcache]
      - recipe[phpstack::varnish]
      - recipe[phpstack::rabbitmq]
      - recipe[phpstack::redis_single]
      - recipe[phpstack::application_php]

  - name: aio-nginx
    run_list:
      - recipe[phpstack::mysql_base]
      - recipe[phpstack::postgresql_base]
      - recipe[phpstack::mongodb_standalone]
      - recipe[phpstack::memcache]
      - recipe[phpstack::varnish]
      - recipe[phpstack::rabbitmq]
      - recipe[phpstack::redis_single]
      - recipe[phpstack::application_php]
    attributes:
      phpstack:
        webserver: 'nginx'

  - name: application-php-apache
    run_list:
      - recipe[phpstack::application_php]

  - name: application-php-nginx
    run_list:
      - recipe[phpstack::application_php]
    attributes:
      phpstack:
        webserver: 'nginx'

  - name: mysql
    run_list:
      - recipe[phpstack::mysql_base]

  - name: postgresql
    run_list:
      - recipe[phpstack::postgresql_base]
