---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  roles_path: ./test/integration/roles
  attributes:
    phpstack:
      demo:
        enabled: true
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true
    mysql:
      server_root_password: "randompass"
      server_repl_password: "randompass"
      server_debian_password: "randompass"
    holland:
      password: "randompass"
    openssh:
      server:
        password_authentication: 'yes'
        permit_root_login: 'yes'
    cloud:
      public_ipv4: '127.0.0.1'
    platformstack:
      cloud_backup:
        enabled: false
      omnibus_updater:
        enabled: false
      iptables:
        allow_ssh_from_world: true
    rackspace:
      cloud_credentials:
        username: 'racker'
        api_key: 'sekrit'
platforms:
  - name: centos-6.5
    run_list:
    - recipe[yum]

suites:
  - name: aio-nginx
    run_list:
      - recipe[phpstack::mysql_base]
      - recipe[phpstack::postgresql_base]
      - recipe[phpstack::mongodb_standalone]
      - recipe[phpstack::memcache]
      - recipe[phpstack::varnish]
      - recipe[phpstack::rabbitmq]
      - recipe[phpstack::redis_single]
      - recipe[phpstack::application_php]
    attributes:
      phpstack:
        webserver: 'nginx'

