---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  client_rb:
    environment: _default
  attributes:
    platformstack:
      cloudbackup:
        enabled: false
      cloud_monitoring:
        enabled: false
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: centos-6.5
    run_list:
    - recipe[yum]

suites:
  - name: all-in-one
    run_list:
      - recipe[phpstack::mysql_base]
      - recipe[phpstack::mongodb_standalone]
      - recipe[phpstack::memcache]
      - recipe[phpstack::varnish]
      - recipe[phpstack::application_php]
    attributes:
      mysql:
        server_root_password: "randompass"
        server_repl_password: "randompass"
        server_debian_password: "randompass"
      holland:
        password: "randompass"
